# Generated by Django 5.1.6 on 2025-02-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='song')),
                ('singer', models.TextField(default='=LOVE')),
                ('url', models.TextField(default='https://www.youtube.com/')),
                ('samune', models.IntegerField(default='0')),
            ],
            options={
                'db_table': 'music',
            },
        ),
    ]
