# Generated by Django 5.1.6 on 2025-03-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('ip', models.CharField(blank=True, max_length=32, null=True)),
                ('oshi_love', models.CharField(blank=True, max_length=16, null=True)),
                ('oshi_me', models.CharField(blank=True, max_length=16, null=True)),
                ('oshi_joy', models.CharField(blank=True, max_length=16, null=True)),
                ('song_list_json', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_choices',
            },
        ),
        migrations.DeleteModel(
            name='Music',
        ),
    ]
