# Generated by Django 5.1.6 on 2025-03-03 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_userchoice_delete_music'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userchoice',
            old_name='oshi_joy',
            new_name='joy',
        ),
        migrations.RenameField(
            model_name='userchoice',
            old_name='oshi_love',
            new_name='love',
        ),
        migrations.RenameField(
            model_name='userchoice',
            old_name='oshi_me',
            new_name='me',
        ),
        migrations.RenameField(
            model_name='userchoice',
            old_name='song_list_json',
            new_name='song',
        ),
    ]
